name: grocery_mobile_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pinput: 1.2.0
  font_awesome_flutter: 9.1.0
  carousel_slider: 4.0.0
  dots_indicator: 2.0.0
  material_design_icons_flutter: 4.0.5955
  badges: 2.0.1
  animated_bottom_navigation_bar: 0.3.2
  fdottedline: 1.0.1
  table_calendar: 3.0.2
  flutter_phoenix: 1.0.0
  flutter_barcode_scanner: ^2.0.0
  provider: 6.0.3
#  google_maps_flutter: ^2.1.1
  url_launcher: ^6.0.17
  flutter_svg: ^1.0.0
  retrofit: any
  logger: ^1.1.0
#  firebase_core: ^1.17.1
#  firebase_messaging: ^11.2.12
  shared_preferences: ^2.0.13
#  webview_flutter: ^3.0.2
  photo_view: ^0.13.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.4.1+3
  build_runner: ^1.11.5
  json_annotation: ^3.1.1
  json_serializable: ^3.5.2
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/che_logo_s.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.otf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
